platform :ios, '10.0'

target 'SetScheduleTest' do
  use_frameworks!
  
  pod 'LBTATools'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'SwiftDate', '~> 5.0'

  # Pods for SetScheduleTest

  target 'SetScheduleTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SetScheduleTestUITests' do
    # Pods for testing
  end

end
